### PR TITLE
Releasing v2.0.0

### LINKED ISSUE #36: [BUG] - Generated VOR frequency format is not consistent
**Describe the bug**
VOR frequency format is not consistent. 

**To Reproduce**
1.  Freq in [VOR].sct2

**Expected behavior**
All freq should have the same format of xxx.xx?

**Screenshots**
image

### LINKED ISSUE #38: [FEAT REQ.] - ASOS/AWOS freq
Add the ASPS/AWOS frequency to the .APT@@@ data.

### PR DESCRIPTION
**Pull request by Nikolai558**
Releasing V2.0.0

### CODE REVIEW

File: FeBuddyLibrary/Helpers/MessageBoxHelpers.cs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 ﻿using System.Collections.Generic;
-using System.Windows;
+using System.Windows.Forms;
```
Comment (Nikolai558) [inline FeBuddyLibrary/Helpers/MessageBoxHelpers.cs:2]: Why are we using System.Windows.Forms here? This is the Library, it shouldnt know about .Forms....

File: FeBuddyWinFormUI/WinForms/AiracDataForm.Designer.cs [hunk 2]
```diff
@@ -340,20 +341,20 @@ private void InitializeComponent()
...
             this.exitButton.UseVisualStyleBackColor = false;
             this.exitButton.Visible = false;
-            this.exitButton.Click += new System.EventHandler(this.ExitButton_Click);
+            this.exitButton.Click += new System.EventHandler(this.AiracDataExitButton_Click);
             // 
             // menuStrip
             // 
             this.menuStrip.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
-            this.menuStrip.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
+            this.menuStrip.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
```
Comment (Nikolai558) [inline FeBuddyWinFormUI/WinForms/AiracDataForm.Designer.cs:349]: Need to double check fonts for ALL Menu Items. Looks like we are using two different fonts. (Segoe UI and Romantic)

File: FeBuddyWinFormUI/WinForms/AiracDataForm.cs [hunk 3]
```diff
@@ -602,6 +587,8 @@ private void UninstallMenuItem_Click(object sender, EventArgs e)
                         + "IF %FE-BUDDY_TEMP_FOLDER%==FOUND ECHO        -temp\\FE-BUDDY\n"
                         + "IF %FE-BUDDY_APPDATA_FOLDER%==FOUND ECHO        -AppData\\Local\\FE-BUDDY\n"
                         + "IF %FE-BUDDY_SHORTCUT%==FOUND ECHO        -Desktop\\FE-BUDDY Shortcut\n"
+                        + "IF %OLD_START_SHORTCUT%==FOUND ECHO        -Start Menu\\Kyle Sanders\n"
```
Comment (Nikolai558) [inline FeBuddyWinFormUI/WinForms/AiracDataForm.cs:590]: I thought this was changed... It should never create a shortcut for \\Kyle Sanders\\ 

The program should ONLY create a shortcut for \\FE-BUDDY\\

File: FeBuddyWinFormUI/app.manifest [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    <security>
+      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
+        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
+      </requestedPrivileges>
+    </security>
+  </trustInfo>
+
+  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
+    <application>
+      <!-- Windows Vista -->
```
Comment (Nikolai558) [inline FeBuddyWinFormUI/app.manifest:14]: Will this really work on Windows Vista and Up? 

Just need to verify before we update System Requirements in Readme.

File: PublishReleaseInstructions.md [hunk 5]
```diff
@@ -0,0 +1,35 @@
+## Steps to release and push out a new update.
```
Comment (Nikolai558) [inline PublishReleaseInstructions.md:1]: Need to update Publish instructions... We have a script now that will do alot of this portion.

File: upgrade-assistant.clef [hunk 6]
```diff
@@ -0,0 +1,687 @@
+{"@t":"2022-01-11T01:34:04.1191685Z","@mt":"Hosting starting","@l":"Debug","EventId":{"Id":1,"Name":"Starting"},"SourceContext":"Microsoft.Extensions.Hosting.Internal.Host"}
```
Comment (Nikolai558) [inline upgrade-assistant.clef:1]: Does this file need to be in the github repository?

**Review by Nikolai558 — COMMENTED** [review]
Double check review comments. Once comments are resolved, I say this is good to release v2.0.0

File: FeBuddyLibrary/Helpers/MessageBoxHelpers.cs (hunk 1 above)
Comment (Nikolai558) [reply FeBuddyLibrary/Helpers/MessageBoxHelpers.cs:2]: This is needed for right now. However, this will need to be addressed at some point as the library shouldn't know anything about the UI.

File: FeBuddyWinFormUI/WinForms/AiracDataForm.Designer.cs (hunk 2 above)
Comment (Nikolai558) [reply FeBuddyWinFormUI/WinForms/AiracDataForm.Designer.cs:349]: Fonts are manually changed in the code. These fonts here are only what fonts are displayed inside visual studio design editor.

File: FeBuddyWinFormUI/WinForms/AiracDataForm.cs (hunk 3 above)
Comment (Nikolai558) [reply FeBuddyWinFormUI/WinForms/AiracDataForm.cs:590]: It was changed. This is just for uninstalling. It only checks if it exists, if it doesn't then it continues.
